/**
 * @module constants/stocksData
 * @description مصدر البيانات الثابتة -- القطاعات والتقييمات فقط
 * الأسماء والأسعار تأتي من sahmk API عبر usePriceUpdater
 */

// ═══════════════════════════════════════════════════════════
// 📊 STOCKS -- رموز تاسي مع القطاع والتقييم فقط
// الأسماء والأسعار: من sahmk API
// oilCorr: للأسهم المرتبطة بالنفط فقط
// ═══════════════════════════════════════════════════════════

export const STOCKS = [
  { sym:"1010", sec:"بنوك",           sectorId:"banks",       rating:75 },
  { sym:"1020", sec:"بنوك",           sectorId:"banks",       rating:70 },
  { sym:"1030", sec:"بنوك",           sectorId:"banks",       rating:70 },
  { sym:"1050", sec:"بنوك",           sectorId:"banks",       rating:72 },
  { sym:"1060", sec:"بنوك",           sectorId:"banks",       rating:74 },
  { sym:"1080", sec:"بنوك",           sectorId:"banks",       rating:73 },
  { sym:"1111", sec:"خدمات مالية",    sectorId:"financial",   rating:70 },
  { sym:"1120", sec:"بنوك",           sectorId:"banks",       rating:82 },
  { sym:"1140", sec:"بنوك",           sectorId:"banks",       rating:74 },
  { sym:"1150", sec:"بنوك",           sectorId:"banks",       rating:74 },
  { sym:"1180", sec:"بنوك",           sectorId:"banks",       rating:78 },
  { sym:"1182", sec:"خدمات مالية",    sectorId:"financial",   rating:60 },
  { sym:"1183", sec:"تقنية",          sectorId:"tech",        rating:65 },
  { sym:"1201", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1202", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1210", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:62 },
  { sym:"1211", sec:"تعدين",          sectorId:"materials",   rating:74 },
  { sym:"1212", sec:"صناعة",          sectorId:"industrial",  rating:65 },
  { sym:"1213", sec:"تجزئة",          sectorId:"retail",      rating:62 },
  { sym:"1214", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1301", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"1302", sec:"صناعة",          sectorId:"industrial",  rating:65 },
  { sym:"1303", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"1304", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"1320", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1321", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1322", sec:"تعدين",          sectorId:"materials",   rating:63 },
  { sym:"1323", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1324", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"1810", sec:"سياحة",          sectorId:"tourism",     rating:65 },
  { sym:"1820", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"1830", sec:"سياحة",          sectorId:"tourism",     rating:67 },
  { sym:"1831", sec:"خدمات",          sectorId:"services",    rating:65 },
  { sym:"1832", sec:"لوجستية",        sectorId:"logistics",   rating:65 },
  { sym:"1833", sec:"خدمات",          sectorId:"services",    rating:63 },
  { sym:"1834", sec:"خدمات",          sectorId:"services",    rating:63 },
  { sym:"1835", sec:"خدمات",          sectorId:"services",    rating:63 },
  { sym:"2001", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:63 },
  { sym:"2010", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:72,  oilCorr:0.65 },
  { sym:"2020", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:68,  oilCorr:0.60 },
  { sym:"2030", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:65 },
  { sym:"2040", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"2050", sec:"أغذية",          sectorId:"food",        rating:68 },
  { sym:"2060", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:67 },
  { sym:"2070", sec:"رعاية صحية",     sectorId:"healthcare",  rating:65 },
  { sym:"2080", sec:"طاقة",           sectorId:"energy",      rating:67,  oilCorr:0.70 },
  { sym:"2081", sec:"طاقة",           sectorId:"energy",      rating:63 },
  { sym:"2082", sec:"طاقة متجددة",    sectorId:"utilities",   rating:80 },
  { sym:"2083", sec:"طاقة متجددة",    sectorId:"utilities",   rating:72 },
  { sym:"2084", sec:"مرافق",          sectorId:"utilities",   rating:65 },
  { sym:"2090", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"2100", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:62 },
  { sym:"2110", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"2120", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:63 },
  { sym:"2130", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2140", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"2150", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"2160", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"2170", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:63 },
  { sym:"2180", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2190", sec:"خدمات",          sectorId:"services",    rating:62 },
  { sym:"2200", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2210", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:62 },
  { sym:"2220", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2222", sec:"طاقة",           sectorId:"energy",      rating:88,  oilCorr:0.85 },
  { sym:"2223", sec:"طاقة",           sectorId:"energy",      rating:70,  oilCorr:0.75 },
  { sym:"2230", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:65 },
  { sym:"2240", sec:"صناعة",          sectorId:"industrial",  rating:65 },
  { sym:"2250", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:63 },
  { sym:"2270", sec:"أغذية",          sectorId:"food",        rating:67 },
  { sym:"2280", sec:"أغذية",          sectorId:"food",        rating:74 },
  { sym:"2281", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2282", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2283", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2284", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2285", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2286", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"2287", sec:"أغذية",          sectorId:"food",        rating:63 },
  { sym:"2288", sec:"أغذية",          sectorId:"food",        rating:63 },
  { sym:"2290", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:67,  oilCorr:0.55 },
  { sym:"2300", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"2310", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:65 },
  { sym:"2320", sec:"صناعة",          sectorId:"industrial",  rating:65 },
  { sym:"2330", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:67,  oilCorr:0.55 },
  { sym:"2340", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2350", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:63 },
  { sym:"2360", sec:"مواد بناء",      sectorId:"materials",   rating:62 },
  { sym:"2370", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"2380", sec:"بتروكيماويات",   sectorId:"petrochem",   rating:62,  oilCorr:0.70 },
  { sym:"2381", sec:"طاقة",           sectorId:"energy",      rating:68,  oilCorr:0.60 },
  { sym:"2382", sec:"طاقة",           sectorId:"energy",      rating:65 },
  { sym:"3002", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3003", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3004", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3005", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3007", sec:"تجزئة",          sectorId:"retail",      rating:62 },
  { sym:"3008", sec:"تجزئة",          sectorId:"retail",      rating:62 },
  { sym:"3010", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3020", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3030", sec:"مواد بناء",      sectorId:"materials",   rating:67 },
  { sym:"3040", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3050", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3060", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3080", sec:"مواد بناء",      sectorId:"materials",   rating:65 },
  { sym:"3090", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3091", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"3092", sec:"مواد بناء",      sectorId:"materials",   rating:63 },
  { sym:"4001", sec:"تجزئة",          sectorId:"retail",      rating:75 },
  { sym:"4002", sec:"رعاية صحية",     sectorId:"healthcare",  rating:78 },
  { sym:"4003", sec:"تجزئة",          sectorId:"retail",      rating:70 },
  { sym:"4004", sec:"رعاية صحية",     sectorId:"healthcare",  rating:75 },
  { sym:"4005", sec:"رعاية صحية",     sectorId:"healthcare",  rating:70 },
  { sym:"4006", sec:"تجزئة",          sectorId:"retail",      rating:70 },
  { sym:"4007", sec:"رعاية صحية",     sectorId:"healthcare",  rating:68 },
  { sym:"4008", sec:"تجزئة",          sectorId:"retail",      rating:68 },
  { sym:"4009", sec:"رعاية صحية",     sectorId:"healthcare",  rating:70 },
  { sym:"4011", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4012", sec:"تجزئة",          sectorId:"retail",      rating:63 },
  { sym:"4013", sec:"رعاية صحية",     sectorId:"healthcare",  rating:80 },
  { sym:"4014", sec:"رعاية صحية",     sectorId:"healthcare",  rating:67 },
  { sym:"4015", sec:"رعاية صحية",     sectorId:"healthcare",  rating:72 },
  { sym:"4016", sec:"رعاية صحية",     sectorId:"healthcare",  rating:68 },
  { sym:"4017", sec:"رعاية صحية",     sectorId:"healthcare",  rating:70 },
  { sym:"4018", sec:"رعاية صحية",     sectorId:"healthcare",  rating:67 },
  { sym:"4019", sec:"رعاية صحية",     sectorId:"healthcare",  rating:67 },
  { sym:"4020", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4021", sec:"رعاية صحية",     sectorId:"healthcare",  rating:67 },
  { sym:"4030", sec:"نقل وخدمات",     sectorId:"transport",   rating:70 },
  { sym:"4031", sec:"نقل وخدمات",     sectorId:"transport",   rating:68 },
  { sym:"4040", sec:"نقل وخدمات",     sectorId:"transport",   rating:63 },
  { sym:"4050", sec:"نقل وخدمات",     sectorId:"transport",   rating:65 },
  { sym:"4051", sec:"تجزئة",          sectorId:"retail",      rating:62 },
  { sym:"4061", sec:"أغذية",          sectorId:"food",        rating:63 },
  { sym:"4070", sec:"إعلام",          sectorId:"media",       rating:62 },
  { sym:"4071", sec:"إعلام",          sectorId:"media",       rating:63 },
  { sym:"4072", sec:"إعلام",          sectorId:"media",       rating:68 },
  { sym:"4080", sec:"خدمات مالية",    sectorId:"financial",   rating:63 },
  { sym:"4081", sec:"خدمات مالية",    sectorId:"financial",   rating:63 },
  { sym:"4082", sec:"تقنية",          sectorId:"tech",        rating:65 },
  { sym:"4083", sec:"تقنية",          sectorId:"tech",        rating:65 },
  { sym:"4084", sec:"خدمات مالية",    sectorId:"financial",   rating:65 },
  { sym:"4090", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4100", sec:"عقارات",         sectorId:"realestate",  rating:65 },
  { sym:"4110", sec:"لوجستية",        sectorId:"logistics",   rating:63 },
  { sym:"4130", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"4140", sec:"نقل وخدمات",     sectorId:"transport",   rating:62 },
  { sym:"4141", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"4142", sec:"صناعة",          sectorId:"industrial",  rating:65 },
  { sym:"4143", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"4144", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"4145", sec:"طاقة",           sectorId:"energy",      rating:62 },
  { sym:"4146", sec:"طاقة",           sectorId:"energy",      rating:62 },
  { sym:"4147", sec:"خدمات",          sectorId:"services",    rating:62 },
  { sym:"4148", sec:"صناعة",          sectorId:"industrial",  rating:62 },
  { sym:"4150", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4160", sec:"تجزئة",          sectorId:"retail",      rating:63 },
  { sym:"4161", sec:"تجزئة",          sectorId:"retail",      rating:75 },
  { sym:"4162", sec:"أغذية",          sectorId:"food",        rating:68 },
  { sym:"4163", sec:"رعاية صحية",     sectorId:"healthcare",  rating:68 },
  { sym:"4164", sec:"رعاية صحية",     sectorId:"healthcare",  rating:78 },
  { sym:"4165", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4170", sec:"سياحة",          sectorId:"tourism",     rating:63 },
  { sym:"4180", sec:"تجزئة",          sectorId:"retail",      rating:63 },
  { sym:"4190", sec:"تجزئة",          sectorId:"retail",      rating:80 },
  { sym:"4191", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4192", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4193", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4194", sec:"تجزئة",          sectorId:"retail",      rating:63 },
  { sym:"4200", sec:"نقل وخدمات",     sectorId:"transport",   rating:68 },
  { sym:"4210", sec:"إعلام",          sectorId:"media",       rating:65 },
  { sym:"4220", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4230", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"4240", sec:"تجزئة",          sectorId:"retail",      rating:65 },
  { sym:"4250", sec:"عقارات",         sectorId:"realestate",  rating:65 },
  { sym:"4260", sec:"نقل وخدمات",     sectorId:"transport",   rating:65 },
  { sym:"4261", sec:"نقل وخدمات",     sectorId:"transport",   rating:68 },
  { sym:"4262", sec:"نقل وخدمات",     sectorId:"transport",   rating:65 },
  { sym:"4263", sec:"نقل وخدمات",     sectorId:"transport",   rating:68 },
  { sym:"4264", sec:"نقل وخدمات",     sectorId:"transport",   rating:65 },
  { sym:"4265", sec:"نقل وخدمات",     sectorId:"transport",   rating:63 },
  { sym:"4270", sec:"صناعة",          sectorId:"industrial",  rating:63 },
  { sym:"4280", sec:"عقارات",         sectorId:"realestate",  rating:68 },
  { sym:"4290", sec:"تعليم",          sectorId:"education",   rating:65 },
  { sym:"4291", sec:"تعليم",          sectorId:"education",   rating:65 },
  { sym:"4292", sec:"تعليم",          sectorId:"education",   rating:65 },
  { sym:"4300", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"4310", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4320", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4321", sec:"عقارات",         sectorId:"realestate",  rating:65 },
  { sym:"4322", sec:"عقارات",         sectorId:"realestate",  rating:65 },
  { sym:"4323", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4324", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4325", sec:"عقارات",         sectorId:"realestate",  rating:63 },
  { sym:"4326", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"4327", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"5110", sec:"طاقة",           sectorId:"energy",      rating:67 },
  { sym:"6001", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"6002", sec:"أغذية",          sectorId:"food",        rating:68 },
  { sym:"6004", sec:"أغذية",          sectorId:"food",        rating:68 },
  { sym:"6010", sec:"زراعة",          sectorId:"agriculture", rating:65 },
  { sym:"6012", sec:"أغذية",          sectorId:"food",        rating:63 },
  { sym:"6013", sec:"أغذية",          sectorId:"food",        rating:63 },
  { sym:"6014", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"6015", sec:"أغذية",          sectorId:"food",        rating:68 },
  { sym:"6016", sec:"أغذية",          sectorId:"food",        rating:65 },
  { sym:"6017", sec:"تقنية",          sectorId:"tech",        rating:68 },
  { sym:"6018", sec:"سياحة",          sectorId:"tourism",     rating:63 },
  { sym:"6019", sec:"نقل وخدمات",     sectorId:"transport",   rating:63 },
  { sym:"6020", sec:"زراعة",          sectorId:"agriculture", rating:63 },
  { sym:"6040", sec:"زراعة",          sectorId:"agriculture", rating:63 },
  { sym:"6050", sec:"زراعة",          sectorId:"agriculture", rating:62 },
  { sym:"6060", sec:"عقارات",         sectorId:"realestate",  rating:62 },
  { sym:"6070", sec:"زراعة",          sectorId:"agriculture", rating:63 },
  { sym:"6090", sec:"طاقة",           sectorId:"energy",      rating:65,  oilCorr:0.55 },
  { sym:"7010", sec:"اتصالات",        sectorId:"telecom",     rating:80 },
];

// ═══════════════════════════════════════════════════════════
// 🗺️ STOCKS_MAP -- وصول سريع بالرمز للقطاع والتقييم
// ═══════════════════════════════════════════════════════════

export const STOCKS_MAP = Object.fromEntries(STOCKS.map(s => [s.sym, s]));

// ═══════════════════════════════════════════════════════════
// 🏭 SECTORS -- القطاعات مع الألوان
// ═══════════════════════════════════════════════════════════

export const SECTORS = [
  { id:'banks',        name:'بنوك',              color:'#4d9fff' },
  { id:'energy',       name:'طاقة',              color:'#f97316' },
  { id:'petrochem',    name:'بتروكيماويات',      color:'#a78bfa' },
  { id:'telecom',      name:'اتصالات',           color:'#22d3ee' },
  { id:'tech',         name:'تقنية',             color:'#06b6d4' },
  { id:'materials',    name:'تعدين ومواد',       color:'#f0c050' },
  { id:'retail',       name:'تجزئة',             color:'#34d399' },
  { id:'food',         name:'أغذية',             color:'#10b981' },
  { id:'utilities',    name:'طاقة متجددة',       color:'#6ee7b7' },
  { id:'realestate',   name:'عقارات',            color:'#fb7185' },
  { id:'insurance',    name:'تأمين',             color:'#818cf8' },
  { id:'tourism',      name:'سياحة وترفيه',      color:'#fbbf24' },
  { id:'logistics',    name:'لوجستية',           color:'#94a3b8' },
  { id:'healthcare',   name:'رعاية صحية',        color:'#f472b6' },
  { id:'financial',    name:'خدمات مالية',       color:'#a78bfa' },
  { id:'construction', name:'مقاولات وبناء',     color:'#78716c' },
  { id:'transport',    name:'نقل ولوجستية',      color:'#60a5fa' },
  { id:'agriculture',  name:'زراعة وأغذية',      color:'#4ade80' },
  { id:'education',    name:'تعليم',             color:'#e879f9' },
  { id:'media',        name:'إعلام',             color:'#94a3b8' },
  { id:'services',     name:'خدمات',             color:'#64748b' },
  { id:'industrial',   name:'صناعة',             color:'#78716c' },
];

export const SECTORS_EXTENDED = [...SECTORS];

// ═══════════════════════════════════════════════════════════
// 📈 INDICES -- المؤشرات الرئيسية
// ═══════════════════════════════════════════════════════════

export const INDICES = [
  { id:'TASI', name:'تاسي', sym:'TASI.SR', type:'main' },
  { id:'NOMU', name:'نمو',  sym:'NOMU.SR', type:'main' },
];

export default STOCKS;

// ═══════════════════════════════════════════════════════════
// 🔄 STOCKS_LIVE -- تبدأ فارغة وتُملأ من sahmk API
// لا تعرض بيانات قديمة عند التحميل
// ═══════════════════════════════════════════════════════════

export let STOCKS_LIVE = [];

export function updateLiveStocks(newStocks) {
  if (!Array.isArray(newStocks) || newStocks.length === 0) return;
  STOCKS_LIVE = newStocks;
}
