/**
 * stocksData.js — SINGLE SOURCE OF TRUTH
 * مبني من بيانات sahmk الحقيقية
 * الأسعار تُحدَّث من API عبر usePriceUpdater
 */

export const STOCKS = [
  { sym:"1010", name:"الرياض",                    sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:75 },
  { sym:"1020", name:"الجزيرة",                   sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"1030", name:"الاستثمار",                  sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"1050", name:"بي اس اف",                  sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:72 },
  { sym:"1060", name:"الأول",                     sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:74 },
  { sym:"1080", name:"العربي",                    sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:73 },
  { sym:"1111", name:"مجموعة تداول",              sec:"خدمات مالية",    sectorId:"financial",   p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"1120", name:"الراجحي",                   sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:82 },
  { sym:"1140", name:"البلاد",                    sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:74 },
  { sym:"1150", name:"الإنماء",                   sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:74 },
  { sym:"1180", name:"الأهلي",                    sec:"بنوك",           sectorId:"banks",       p:0, ch:0, pct:0, v:0, avgV:0, rating:78 },
  { sym:"1182", name:"أملاك",                     sec:"خدمات مالية",    sectorId:"financial",   p:0, ch:0, pct:0, v:0, avgV:0, rating:60 },
  { sym:"1183", name:"سهل",                       sec:"تقنية",          sectorId:"tech",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1201", name:"تكوين",                     sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1202", name:"مبكو",                      sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1210", name:"بي سي آي",                 sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1211", name:"معادن",                     sec:"تعدين",          sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:74 },
  { sym:"1212", name:"أسترا الصناعية",            sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1213", name:"نسيج",                      sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1214", name:"شاكر",                      sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1301", name:"أسلاك",                     sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1302", name:"بوان",                      sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1303", name:"الصناعات الكهربائية",        sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1304", name:"اليمامة للحديد",             sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1320", name:"أنابيب السعودية",            sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1321", name:"أنابيب الشرق",              sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1322", name:"أماك",                      sec:"تعدين",          sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1323", name:"يو سي آي سي",              sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1324", name:"صالح الراشد",               sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1810", name:"سيرا",                      sec:"سياحة",          sectorId:"tourism",     p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1820", name:"بان",                       sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"1830", name:"لجام للرياضة",              sec:"سياحة",          sectorId:"tourism",     p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"1831", name:"مهارة",                     sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1832", name:"صدر",                       sec:"لوجستية",        sectorId:"logistics",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"1833", name:"الموارد",                   sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1834", name:"سماسكو",                    sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"1835", name:"تمكين",                     sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2001", name:"كيمانول",                   sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2010", name:"سابك",                      sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:72 },
  { sym:"2020", name:"سابك للمغذيات الزراعية",    sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"2030", name:"المصافي",                   sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2040", name:"الخزف السعودي",              sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2050", name:"مجموعة صافولا",              sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"2060", name:"التصنيع",                   sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"2070", name:"الدوائية",                  sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2080", name:"الغاز",                     sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"2081", name:"الخريف",                    sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2082", name:"أكوا",                      sec:"طاقة متجددة",    sectorId:"utilities",   p:0, ch:0, pct:0, v:0, avgV:0, rating:80 },
  { sym:"2083", name:"مرافق",                     sec:"طاقة متجددة",    sectorId:"utilities",   p:0, ch:0, pct:0, v:0, avgV:0, rating:72 },
  { sym:"2084", name:"مياهنا",                    sec:"مرافق",          sectorId:"utilities",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2090", name:"جبسكو",                     sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2100", name:"وفرة",                      sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2110", name:"الكابلات السعودية",          sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2120", name:"متطورة",                    sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2130", name:"صدق",                       sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2140", name:"أيان",                      sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2150", name:"زجاج",                      sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2160", name:"أميانتيت",                  sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2170", name:"اللجين",                    sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2180", name:"فيبكو",                     sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2190", name:"سيسكو القابضة",             sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2200", name:"أنابيب",                    sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2210", name:"نماء للكيماويات",            sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2220", name:"معدنية",                    sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2222", name:"أرامكو السعودية",            sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:88 },
  { sym:"2223", name:"لوبريف",                    sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"2230", name:"الكيمائية",                 sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2240", name:"صناعات",                    sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2250", name:"المجموعة السعودية",          sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2270", name:"سدافكو",                    sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"2280", name:"المراعي",                   sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:74 },
  { sym:"2281", name:"تنمية",                     sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2282", name:"نقي",                       sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2283", name:"المطاحن الأولى",             sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2284", name:"المطاحن الحديثة",            sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2285", name:"المطاحن العربية",            sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2286", name:"المطاحن الرابعة",            sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2287", name:"إنتاج",                     sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2288", name:"نفوذ",                      sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2290", name:"ينساب",                     sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"2300", name:"صناعة الورق",               sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2310", name:"سبكيم العالمية",             sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2320", name:"البابطين",                  sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"2330", name:"المتقدمة",                  sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"2340", name:"أرتيكس",                    sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2350", name:"كيان السعودية",              sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"2360", name:"الفخارية",                  sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2370", name:"مسك",                       sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2380", name:"بترو رابغ",                 sec:"بتروكيماويات",   sectorId:"petrochem",   p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"2381", name:"الحفر العربية",              sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"2382", name:"أديس",                      sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3002", name:"أسمنت نجران",               sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3003", name:"أسمنت المدينة",             sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3004", name:"أسمنت الشمالية",            sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3005", name:"أسمنت ام القرى",            sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3007", name:"الواحة",                    sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"3008", name:"الكثيري",                   sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"3010", name:"أسمنت العربية",             sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3020", name:"أسمنت اليمامة",             sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3030", name:"أسمنت السعودية",            sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"3040", name:"أسمنت القصيم",              sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3050", name:"أسمنت الجنوب",              sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3060", name:"أسمنت ينبع",                sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3080", name:"أسمنت الشرقية",             sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"3090", name:"أسمنت تبوك",                sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3091", name:"أسمنت الجوف",               sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"3092", name:"أسمنت الرياض",              sec:"مواد بناء",      sectorId:"materials",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4001", name:"أسواق ع العثيم",            sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:75 },
  { sym:"4002", name:"المواساة",                  sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:78 },
  { sym:"4003", name:"إكسترا",                    sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4004", name:"دله الصحية",                sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:75 },
  { sym:"4005", name:"رعاية",                     sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4006", name:"أسواق المزرعة",             sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4007", name:"الحمادي",                   sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4008", name:"ساكو",                      sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4009", name:"السعودي الألماني الصحية",   sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4011", name:"لازوردي",                   sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4012", name:"الأصيل",                    sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4013", name:"سليمان الحبيب",             sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:80 },
  { sym:"4014", name:"دار المعدات",               sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"4015", name:"جمجوم فارما",               sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:72 },
  { sym:"4016", name:"أفالون فارما",              sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4017", name:"فقيه الطبية",               sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4018", name:"الموسى",                    sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"4019", name:"اس ام سي",                 sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"4020", name:"العقارية",                  sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4021", name:"المركز الكندي الطبي",       sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"4030", name:"البحري",                    sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:70 },
  { sym:"4031", name:"الخدمات الأرضية",           sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4040", name:"سابتكو",                    sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4050", name:"ساسكو",                     sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4051", name:"باعظيم",                    sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4061", name:"أنعام القابضة",              sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4070", name:"تهامة",                     sec:"إعلام",          sectorId:"media",       p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4071", name:"العربية",                   sec:"إعلام",          sectorId:"media",       p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4072", name:"مجموعة إم بي سي",           sec:"إعلام",          sectorId:"media",       p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4080", name:"سناد القابضة",              sec:"خدمات مالية",    sectorId:"financial",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4081", name:"النايفات",                  sec:"خدمات مالية",    sectorId:"financial",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4082", name:"مرنة",                      sec:"تقنية",          sectorId:"tech",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4083", name:"تسهيل",                     sec:"تقنية",          sectorId:"tech",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4084", name:"دراية",                     sec:"خدمات مالية",    sectorId:"financial",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4090", name:"طيبة",                      sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4100", name:"مكة",                       sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4110", name:"باتك",                      sec:"لوجستية",        sectorId:"logistics",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4130", name:"الباحة",                    sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4140", name:"صادرات",                    sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4141", name:"العمران",                   sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4142", name:"كابلات الرياض",             sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4143", name:"تالكو",                     sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4144", name:"رؤوم",                      sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4145", name:"أو جي سي",                 sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4146", name:"جاز",                       sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4147", name:"سي جي إس",                 sec:"خدمات",          sectorId:"services",    p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4148", name:"الوسائل الصناعية",          sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4150", name:"التعمير",                   sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4160", name:"ثمار",                      sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4161", name:"بن داود",                   sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:75 },
  { sym:"4162", name:"المنجم",                    sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4163", name:"الدواء",                    sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4164", name:"النهدي",                    sec:"رعاية صحية",     sectorId:"healthcare",  p:0, ch:0, pct:0, v:0, avgV:0, rating:78 },
  { sym:"4165", name:"الماجد للعود",              sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4170", name:"شمس",                       sec:"سياحة",          sectorId:"tourism",     p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4180", name:"مجموعة فتيحي",              sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4190", name:"جرير",                      sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:80 },
  { sym:"4191", name:"أبو معطي",                  sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4192", name:"السيف غاليري",              sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4193", name:"نايس ون",                   sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4194", name:"محطة البناء",               sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4200", name:"الدريس",                    sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4210", name:"الأبحاث والإعلام",          sec:"إعلام",          sectorId:"media",       p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4220", name:"إعمار",                     sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4230", name:"البحر الأحمر",              sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4240", name:"سينومي ريتيل",             sec:"تجزئة",          sectorId:"retail",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4250", name:"جبل عمر",                   sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4260", name:"بدجت السعودية",             sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4261", name:"ذيب",                       sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4262", name:"لومي",                      sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4263", name:"سال",                       sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4264", name:"طيران ناس",                 sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4265", name:"شري",                       sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4270", name:"طباعة وتغليف",             sec:"صناعة",          sectorId:"industrial",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4280", name:"المملكة",                   sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"4290", name:"الخليج للتدريب",            sec:"تعليم",          sectorId:"education",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4291", name:"الوطنية للتعليم",           sec:"تعليم",          sectorId:"education",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4292", name:"عطاء",                      sec:"تعليم",          sectorId:"education",   p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4300", name:"دار الأركان",               sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4310", name:"مدينة المعرفة",             sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4320", name:"الأندلس",                   sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4321", name:"سينومي سنترز",             sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4322", name:"رتال",                      sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"4323", name:"سمو",                       sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4324", name:"بنان",                      sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4325", name:"مسار",                      sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"4326", name:"الماجدية",                  sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"4327", name:"الرمز",                     sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"5110", name:"السعودية للكهرباء",         sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:67 },
  { sym:"6001", name:"حلواني إخوان",              sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"6002", name:"هرفي للأغذية",              sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"6004", name:"كاتريون",                   sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"6010", name:"نادك",                      sec:"زراعة",          sectorId:"agriculture", p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"6012", name:"ريدان",                     sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6013", name:"التطويرية الغذائية",        sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6014", name:"الآمار",                    sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"6015", name:"أمريكانا",                  sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"6016", name:"برغرايزر",                  sec:"أغذية",          sectorId:"food",        p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"6017", name:"جاهز",                      sec:"تقنية",          sectorId:"tech",        p:0, ch:0, pct:0, v:0, avgV:0, rating:68 },
  { sym:"6018", name:"الأندية للرياضة",           sec:"سياحة",          sectorId:"tourism",     p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6019", name:"المسار الشامل",             sec:"نقل وخدمات",     sectorId:"transport",   p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6020", name:"جاكو",                      sec:"زراعة",          sectorId:"agriculture", p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6040", name:"تبوك الزراعية",             sec:"زراعة",          sectorId:"agriculture", p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6050", name:"الأسماك",                   sec:"زراعة",          sectorId:"agriculture", p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"6060", name:"الشرقية للتنمية",           sec:"عقارات",         sectorId:"realestate",  p:0, ch:0, pct:0, v:0, avgV:0, rating:62 },
  { sym:"6070", name:"الجوف",                     sec:"زراعة",          sectorId:"agriculture", p:0, ch:0, pct:0, v:0, avgV:0, rating:63 },
  { sym:"6090", name:"جازادكو",                   sec:"طاقة",           sectorId:"energy",      p:0, ch:0, pct:0, v:0, avgV:0, rating:65 },
  { sym:"7010", name:"اس تي سي",                 sec:"تقنية",          sectorId:"telecom",     p:0, ch:0, pct:0, v:0, avgV:0, rating:80 },
];

export const STOCKS_MAP = Object.fromEntries(STOCKS.map(s => [s.sym, s]));

export const SECTORS = [
  { id:'energy',       name:'طاقة',              color:'#f97316' },
  { id:'banks',        name:'بنوك',              color:'#4d9fff' },
  { id:'petrochem',    name:'بتروكيماويات',      color:'#a78bfa' },
  { id:'telecom',      name:'تقنية واتصالات',    color:'#22d3ee' },
  { id:'tech',         name:'تقنية',             color:'#22d3ee' },
  { id:'materials',    name:'تعدين ومواد',       color:'#f0c050' },
  { id:'retail',       name:'تجزئة',             color:'#34d399' },
  { id:'food',         name:'أغذية',             color:'#10b981' },
  { id:'utilities',    name:'طاقة متجددة',       color:'#6ee7b7' },
  { id:'realestate',   name:'عقارات',            color:'#fb7185' },
  { id:'insurance',    name:'تأمين',             color:'#818cf8' },
  { id:'tourism',      name:'سياحة وترفيه',      color:'#fbbf24' },
  { id:'logistics',    name:'لوجستية',           color:'#94a3b8' },
  { id:'healthcare',   name:'رعاية صحية',        color:'#f472b6' },
  { id:'financial',    name:'خدمات مالية',       color:'#a78bfa' },
  { id:'construction', name:'مقاولات وبناء',     color:'#78716c' },
  { id:'transport',    name:'نقل ولوجستية',      color:'#60a5fa' },
  { id:'agriculture',  name:'زراعة وأغذية',      color:'#4ade80' },
  { id:'education',    name:'تعليم',             color:'#f472b6' },
  { id:'media',        name:'إعلام',             color:'#94a3b8' },
  { id:'services',     name:'خدمات',             color:'#94a3b8' },
  { id:'industrial',   name:'صناعة',             color:'#78716c' },
];

export const SECTORS_EXTENDED = [...SECTORS];

export const INDICES = [
  { id: 'TASI', name: 'تاسي', sym: 'TASI.SR', type: 'main' },
  { id: 'NOMU', name: 'نمو',  sym: 'NOMU.SR', type: 'main' },
];

export default STOCKS;
export let STOCKS_LIVE = STOCKS;

export function updateLiveStocks(newStocks) {
  STOCKS_LIVE = newStocks;
}
